#
# Labtainer Dockerfile
#
# The labtainer.base image includes the following packages:
# build-essential  expect  file  gcc-multilib  gdb  iputils-ping  less  man  manpages-dev 
# net-tools  openssh-client  python  sudo  tcl8.6  vim  zip  hexedit  rsyslog
#
# The labtainer.network image adds the following packages:
# openssl openssh-server openvpn wget tcpdump  update-inetd  xinetd
#
ARG registry
FROM $registry/labtainer.network2
FROM $registry/labtainer.network.ssh2
#
#  lab is the fully qualified image name, e.g., mylab.some_container.student
#  labdir is the name of the lab, e.g., mylab 
#  imagedir is the name of the container
#  user_name is the USER from the start.config, if other than ubuntu,
#            then that user must be added in this dockerfile
#            before the USER command
#
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

# Install rsyslog and configure logging for SSH
RUN apt-get update && apt-get install -y rsyslog && \
    sed -i '/imklog/s/^/#/' /etc/rsyslog.conf && \
    echo "auth,authpriv.* /var/log/ssh.log" >> /etc/rsyslog.d/50-default.conf && \
    service rsyslog restart

# Configure SSH logging level to verbose
RUN sed -i 's/#LogLevel INFO/LogLevel VERBOSE/' /etc/ssh/sshd_config && \
    echo "LogLevel VERBOSE" >> /etc/ssh/sshd_config && \
    service ssh restart

# Create the user and set the password
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo
RUN useradd -ms /bin/bash user1 && \
    echo "user1:password" | chpasswd && \
    echo "user1 ALL=(ALL) NOPASSWD: /usr/sbin/useradd, /usr/bin/passwd" >> /etc/sudoers

# Create log directory and initialize log file
RUN mkdir -p /var/log && touch /var/log/ssh.log && \
    chown syslog:adm /var/log/ssh.log

# Switch to the user
USER $user_name
ENV HOME /home/$user_name

# Install files in the user home directory
ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME

# Switch back to root to start services
USER root
CMD service rsyslog start && service ssh start && tail -f /var/log/ssh.log
